### ISSUE TITLE
Improve new location submission UX

### ISSUE THREAD

**Issue by bdruth** [flexion/msab-arts-locator#172]
As an Art Location submitter, in order to continue using the app, I want the app to take me somewhere useful after I submit a location.

**Acceptance Criteria**:
- [x] After a successful submission, the user is routed back to the main page
- [x] After an error submission, the user remains on the form page
- [x] User receives an alert indicating success or failure.

Proposed new error handling:
> Error messaging - using D8EEEE as the background color. With this language, you don't need different messages for each error. Just list the actual field name in the bullets. @uxforgood 
![image](https://user-images.githubusercontent.com/444571/123150194-b32fcf00-d427-11eb-94b1-98f25c6e27b5.png)

Proposed new success handling:
> Successful submission - I think whether they've enabled use location or not, let's take them to the "disabled" homepage where they'd put in their location to search. The other "homescreen" if they've enabled location is actually the search results screen (they bypass this since we're using their location). But in this flow of submitting a location, I don't think it makes sense to take them to pre-loaded search results. @uxforgood 
![image](https://user-images.githubusercontent.com/444571/123150244-c17deb00-d427-11eb-8d48-b80cdc326ecf.png)

**Tasks**:
- [x] Implement changes
- [x] Test
- [x] Review
- [x] User acceptance

**Comment by xpmuyanja** [comment]
1. Resolved: <successfully submitted Art location>
Message banner display on top of page letting user know the Art location was successfully submitted
![Improve New Art Location Submission](https://user-images.githubusercontent.com/86261039/123816038-99c1d380-d8bc-11eb-8f7d-83b6d2dcbfe2.png)

2. New Art Location - error message on page 
When submitting a new Art  Location and there is a user error, the error message is displayed on top of page (see image)
![New Art Location with an Error](https://user-images.githubusercontent.com/86261039/123817755-0b4e5180-d8be-11eb-87e6-35a424df222b.png)

**Comment by bdruth** [comment]
Thanks @xpmuyanja!
